def custom_song (verb_1, verb_2, verb_3, pronoun_1, pronoun_2, person_1, person_2, place):
    print("\n\n")
    print(f"Do {pronoun_1} know the {person_1}")
    print(f"The {person_1}, the {person_1}")
    print(f"Oh, do {pronoun_1} know the {person_1}")
    print(f"Who {verb_1} on {place}?")
    print(f"Oh yes, {pronoun_2} know the {person_2}")
    print(f"The {person_2}, the {person_2}")
    print(f"Oh yes, {pronoun_2} know the {person_2}")
    print(f"Who {verb_2} on {place}?")
    print(f"Oh, {pronoun_2} all know the {person_1}")
    print(f"The {person_2}, the {person_2}")
    print(f"Oh, {pronoun_2} all know the {person_1}")
    print(f"Who {verb_3} on {place}?")

input_verb_1 = input("Enter a verb: ")
input_verb_2 = input("Enter another verb: ")
input_verb_3 = input("Enter one more verb: ")
input_pronoun_1 = input("Enter a pronoun: ")
input_pronoun_2 = input("Enter another pronoun: ")
input_person_1 = input("Enter a person: ")
input_person_2 = input("Enter another person: ")
input_place = input("Enter a place: ")

custom_song(verb_1=input_verb_1, verb_2=input_verb_2, verb_3=input_verb_3, pronoun_1=input_pronoun_1, pronoun_2=input_pronoun_2, person_1=input_person_1, person_2=input_person_2, place=input_place)